input_groups: list(str())
exclude_root: bool(required=False)
latitude_var: str()
longitude_var: str()
concat_dim: str()
chunks: include('chunks')
drop_vars: list(str(), required=False)

---
chunks:
  latitude: int(min=1)
  longitude: int(min=1)


