input_groups: list(str())
exclude_root: bool(required=False)
latitude_var: str()
longitude_var: str()
time_var: str()
correct_longitude: enum('meridian', 'antimeridian', required=False)
time_reduce: enum('min', 'max', 'mean', 'median', 'sum', required=False)
concat_dim: str()
chunks: include('chunks')
drop_vars: list(str(), required=False)

---
chunks:
  latitude: int(min=1)
  longitude: int(min=1)
  time: int(min=1)


